[package]
name = "eui48-bench"
version = "0.1.0"
authors = ["Felix Schreiner <felix.schreiner@rhebo.com>"]
edition = "2018"

[dependencies]
bincode = "1.3"
eui48 = { git = "https://github.com/felix-rhebo/eui48.git", features = ["serde", "serde_bytes"] }